[package]
name = "nokozero_hook"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Input hooking for nokozero"
readme.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bitflags = "2.11.1"
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
] }

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true
