[package]
name = "nokozero_hook"
version = "0.0.0"
authors = ["Kyle Chen"]
edition = "2024"
rust-version = "1.88"
description = "Input hooking for nokozero"
readme = "../README.md"
repository = "https://github.com/astral4/nokozero"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
bitflags = "2.13.1"
windows = { version = "0.62", default-features = false, features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D9",
    "Win32_Graphics_Gdi",
] }
windows-core = { version = "0.62", default-features = false }
windows-numerics = { version = "0.3", default-features = false }
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_IO",
    "Win32_System_Kernel",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_UI_Controls",
    "Win32_UI_WindowsAndMessaging",
] }

[lib]
crate-type = ["cdylib"]

[lints.rust]
ffi_unwind_calls = "warn"
improper_ctypes = "deny"
improper_ctypes_definitions = "deny"
let_underscore_drop = "deny"
macro_use_extern_crate = "deny"
meta_variable_misuse = "deny"
missing_abi = "deny"
non_ascii_idents = "forbid"
non_local_definitions = "warn"
nonstandard_style = { level = "deny", priority = -1 }
redundant_lifetimes = "deny"
rust_2018_idioms = { level = "deny", priority = -1 }
trivial_casts = "deny"
trivial_numeric_casts = "deny"
unit_bindings = "deny"
unreachable_pub = "deny"
unsafe_op_in_unsafe_fn = "deny"
unused_crate_dependencies = "deny"
unused_import_braces = "deny"
unused_lifetimes = "deny"
unused_macro_rules = "deny"
unused_qualifications = "deny"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
should_panic_without_expect = "allow"
as_ptr_cast_mut = "deny"
big_endian_bytes = "deny"
dbg_macro = "deny"
doc_paragraphs_missing_punctuation = "deny"
exit = "deny"
fn_to_numeric_cast_any = "deny"
host_endian_bytes = "deny"
mem_forget = "deny"
missing_assert_message = "deny"
precedence_bits = "deny"
print_stdout = "deny"
self_named_module_files = "deny"
todo = "deny"
transmute_undefined_repr = "deny"
unimplemented = "deny"
unnecessary_safety_comment = "deny"
unnecessary_safety_doc = "deny"
unused_trait_names = "deny"
wildcard_enum_match_arm = "deny"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
panic = "abort"
