[package]
name = "nokozero_hook"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Input hooking for nokozero"
readme.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bitflags = "2.9.1"
windows = { workspace = true, features = ["Win32_System_SystemServices"] }

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true
