[project]
name = "nokozero"
version = "0.0.0"
description = "Reinforcement learning agent that plays Touhou"
readme = "README.md"
license = "MIT OR Apache-2.0"
authors = [{ name = "Kyle Chen" }]
requires-python = ">=3.14"
dependencies = [
    "equinox>=0.13.8",
    "jax[cuda13]>=0.11.2",
    "jaxtyping>=0.3.11",
    "numpy>=2.5.3",
    "optax>=0.2.8",
]

[project.scripts]
nokozero = "nokozero.cli:main"

[dependency-groups]
dev = ["basedpyright>=1.40.1", "pytest>=9.1.1", "ruff>=0.16.10"]

[build-system]
requires = ["uv_build>=0.12.22,<0.13"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = ["COM812", "CPY001", "D105", "D107", "D203", "D213"]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["D1", "INP001", "PLR2004", "PT018", "S101"]

[tool.basedpyright]
typeCheckingMode = "all"
pythonPlatform = "Linux"
include = ["src", "tests"]
reportAny = false
reportExplicitAny = false
reportImplicitStringConcatenation = false
reportUnannotatedClassAttribute = false
reportUnusedCallResult = false

[[tool.basedpyright.executionEnvironments]]
root = "tests"
reportPrivateUsage = false
